base:
  project: forest-cover-classification
  random_state: 42
  target_col: class

reports:
  fetch_data_report: reports/training_data_fetch_report.json
  validate_data_report: reports/validated_training_filenames_report.json
  training_data_insertion_report: reports/training_data_insertion_report.json
  training_models_report: reports/training_models_report.json
  prediction_data_insertion_reports: reports/prediction_data_insertion_report.json

cloud:
  training_data_folder: forest_cover/data/training_files/
  prediction_data_folder: forest_cover/data/prediction_files/
  bucket_name: modomegabucket
  models_save_path: forest_cover/models/
  clustering_model_name: k_means_clustering_model.pkl
  standard_scalar_model: scalar.pkl
  prediction_schema: prediction_schema.json

database:
  raw_training_data_db: TRAINING_DATA
  raw_bad_data_db: BAD_DATA
  raw_prediction_data_db: PREDICTION_DATA
  predictions_db: PREDICTIONS

training_schema:
  test_size: 0.4
  number_of_columns: 52
  target_label_encodings:
    Lodgepole_Pine: 1
    Spruce_Fir: 2
    Douglas_fir: 3
    Krummholz: 4
    Ponderosa_Pine: 5
    Aspen: 6
    Cottonwood_Willow: 7
  numerical_columns:
    - elevation
    - aspect
    - slope
    - horizontal_distance_to_hydrology
    - vertical_distance_to_hydrology
    - horizontal_distance_to_roadways
    - horizontal_distance_to_fire_points
  column_names:
    - elevation
    - aspect
    - slope
    - horizontal_distance_to_hydrology
    - vertical_distance_to_hydrology
    - horizontal_distance_to_roadways
    - horizontal_distance_to_fire_points
    - wilderness_area1
    - wilderness_area2
    - wilderness_area3
    - wilderness_area4
    - soil_type_1
    - soil_type_2
    - soil_type_3
    - soil_type_4
    - soil_type_5
    - soil_type_6
    - soil_type_7
    - soil_type_8
    - soil_type_9
    - soil_type_10
    - soil_type_11
    - soil_type_12
    - soil_type_13
    - soil_type_14
    - soil_type_15
    - soil_type_16
    - soil_type_17
    - soil_type_18
    - soil_type_19
    - soil_type_20
    - soil_type_21
    - soil_type_22
    - soil_type_23
    - soil_type_24
    - soil_type_25
    - soil_type_26
    - soil_type_27
    - soil_type_28
    - soil_type_29
    - soil_type_30
    - soil_type_31
    - soil_type_32
    - soil_type_33
    - soil_type_34
    - soil_type_35
    - soil_type_36
    - soil_type_37
    - soil_type_38
    - soil_type_39
    - soil_type_40
    - class

prediction_schema:
  number_of_columns: 51
  target_label_encodings:
    Lodgepole_Pine: 1
    Spruce_Fir: 2
    Douglas_fir: 3
    Krummholz: 4
    Ponderosa_Pine: 5
    Aspen: 6
    Cottonwood_Willow: 7
  numerical_columns:
    - elevation
    - aspect
    - slope
    - horizontal_distance_to_hydrology
    - vertical_distance_to_hydrology
    - horizontal_distance_to_roadways
    - horizontal_distance_to_fire_points
  column_names:
    - elevation
    - aspect
    - slope
    - horizontal_distance_to_hydrology
    - vertical_distance_to_hydrology
    - horizontal_distance_to_roadways
    - horizontal_distance_to_fire_points
    - wilderness_area1
    - wilderness_area2
    - wilderness_area3
    - wilderness_area4
    - soil_type_1
    - soil_type_2
    - soil_type_3
    - soil_type_4
    - soil_type_5
    - soil_type_6
    - soil_type_7
    - soil_type_8
    - soil_type_9
    - soil_type_10
    - soil_type_11
    - soil_type_12
    - soil_type_13
    - soil_type_14
    - soil_type_15
    - soil_type_16
    - soil_type_17
    - soil_type_18
    - soil_type_19
    - soil_type_20
    - soil_type_21
    - soil_type_22
    - soil_type_23
    - soil_type_24
    - soil_type_25
    - soil_type_26
    - soil_type_27
    - soil_type_28
    - soil_type_29
    - soil_type_30
    - soil_type_31
    - soil_type_32
    - soil_type_33
    - soil_type_34
    - soil_type_35
    - soil_type_36
    - soil_type_37
    - soil_type_38
    - soil_type_39
    - soil_type_40